services:
  Frp:
    image: 'wnwd/frps:latest'
    container_name: frps
    restart: unless-stopped
    environment:
      CONF_TYPE: 'yml'
      # CONF_TYPE: 'toml'
      # CONF_TYPE: 'json'
    volumes:
      - ./conf:/etc/frp
    network_mode: 'host'